### ISSUE TITLE
Guesser option missing

### ISSUE THREAD

**Issue by jmaximusix** [Eisbison/TheOtherRoles#196]
"Guesser Number Of Shots Per Meeting" - option is mentioned in the docs but doesn't show up in game

**Comment by dwd0tcom** [comment]
This is already fixed:

![image](https://user-images.githubusercontent.com/9768158/139581479-86a146fc-fc79-4c47-81fb-03a6cc0d2a5d.png)

**Comment by jmaximusix** [comment]
This is not true! if you pay close attention, the docs mention two seperate options: number of shots per game and number of shots per meeting. However only one seems to be implemented! I hope this gets reopened as it is NOT fixed
![image](https://user-images.githubusercontent.com/55534834/139927392-37a878cf-cfb9-426d-8c10-b9ccb9f1dd90.png)

**Comment by Eisbison** [comment]
It's been fixed now :)
